### ISSUE TITLE
Router doesn't see Spend as a "new url" when tab is active in Campaigns

### ISSUE THREAD

**Issue by goshadole** [looker/app-marketing-analytics#134]
If you click on a tab other than Spend, then click Campaigns on the left navigation it'll reload the iframe and reset the tab active to Spend.

But if Spend is active, if on the visualizations, if you drill in or hit explore, then click Campaigns in the 
 navigation, it doesn't refresh the iframe like the other tabs do, since Spend is already the active.

**Comment by justinlooker** [comment]
@lukelooker @goshadole did this end up on the wrong board?

**Comment by lukelooker** [comment]
Yep. Re-created as https://github.com/looker/app-host/issues/184
