### ISSUE TITLE
Decrease precision on conversions to whole numbers 

### ISSUE THREAD

**Issue by AnnaSerova** [looker/app-marketing-analytics#146]
![39605435-50bc677c-4ee5-11e8-8c76-6e1f42fe7ceb](https://user-images.githubusercontent.com/20978476/40015072-14414f9e-5767-11e8-92a1-b167d96ec5cf.png)

**Comment by lukelooker** [comment]
Fixed via AppHost PR: https://github.com/looker/app-host/pull/274
