### ISSUE TITLE
measures in google_ad_metrics_base are broken

### ISSUE THREAD

**Issue by jakeyoos** [looker/app-marketing-analytics#147]
```
 measure: total_impressions {
  }
  measure: total_clicks {
  }
  measure: total_conversions {
    drill_fields: [fact.date_date, campaign.campaign_name, fact.total_conversions]
  }
  measure: total_cost {
    drill_fields: [fact.date_date, campaign.campaign_name, fact.total_cost]
  }
```

These measures in `google_ad_metrics_base` overwrite the same metrics from the `ad_metrics_base` but don't have `sql:` properties so break the explore.  I would fix, but apparently can't check out a dev branch!?!!?!?!

**Comment by jdavidson** [comment]
Thanks for the note!

this requires that you've got the full structure of the app now

currently 4 projects:
app_marketing_analytics
ama_adwords_adapter
ama_fb_adapter
app_marketing_analytics_config

where is the broken explore?

**Comment by jakeyoos** [comment]
You mean to enter dev I have to have the full structure?  Eenteresting

https://meta.looker.com/explore/marketing_analytics/period_fact?qid=p2ZjuWSHqGdgSndByU6wNH&toggle=vis

**Comment by AnnaSerova** [comment]
Is this still an issue? Or can we close it? @jdavidson

**Comment by jakeyoos** [comment]
It fixes the problems I was having, so I will close - Thanks!
